version: '3'
services:
  proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - internal
    restart: always
    
  app:
    image: "myapp"
    expose:
      - "5000"
    networks:
      - internal
    restart: always
    environment:
      - APP__APPNAME=${APP_APPNAME}
      - APP__CLIENTID=${APP_CLIENTID}
      - APP__CLIENTSECRET=${APP_CLIENTSECRET}
    
networks:
  internal:
    driver: bridge